Update CICD-Frontend.yml

diff --git a/.github/workflows/CICD-Frontend.yml b/.github/workflows/CICD-Frontend.yml
--- a/.github/workflows/CICD-Frontend.yml
+++ b/.github/workflows/CICD-Frontend.yml
@@ -25,10 +25,42 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
       
+      - name: Build Frontend
+        env:
+            # Accessing the secret variable
+            FTEST_PATH: ${{ secrets.FRONTEND_SOLUTION_PATH }}
+        run: dotnet build "${GITHUB_WORKSPACE}/${FTEST_PATH}"
+    
       - name: Npm install
         run: |
             cd Frontend/angular
             npm install
+            
+      - name: Npmstart
+        id: start-app
+        run: |
+          cd Frontend/angular
+      
+          output_file=$(mktemp)
+      
+          npm start > "$output_file" 2>&1 &
+      
+          start_pid=$!
+      
+          sleep 120
+      
+          if ps -p $start_pid > /dev/null; then
+            kill $start_pid
+          fi
+      
+          if grep -qi "error" "$output_file"; then
+            echo "npm start encountered an error."
+            exit 1
+          else
+            echo "npm start completed without errors."
+          fi
+      
+          rm "$output_file"
             
       - name: Build Frontend
         run: |
@@ -53,11 +85,14 @@ jobs:
       - name: Copy Frontend build to FrontendDist
         env:
             # Accessing the secret variable
-            FFBUILD_PATH: ${{ secrets.BUILD_FRONTEND }}
-        run: cp -R frontend-dist/* "${{ github.workspace }}/${FFBUILD_PATH}"
+            FBUILD_PATH: ${{ secrets.BUILD_FRONTEND }}
+        run: cp -R frontend-dist/* "${{ github.workspace }}/${FBUILD_PATH}"
       
       - name: Display contents of FrontendDist
-        run: ls -R "${{ github.workspace }}/Frontend/angular/FrontendDist"   
+        env:
+            # Accessing the secret variable
+            FBUILD_PATH: ${{ secrets.BUILD_FRONTEND }
+        run: ls -R "${{ github.workspace }}/${FBUILD_PATH}"   
         
   Backend:
     needs: [Frontend]
