Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,11 +62,12 @@ jobs:
           # Kill the npm start process after two minutes
           kill $start_pid
 
-      - name: Check if npm start succeeded
+      - name: Check Npm start status
         run: |
-          if [ ${{ steps.start-app.outcome }} == 'success' ]; then
-            echo "npm start succeeded!"
+          if [ $? -eq 0 ]; then
+            echo "npm start completed successfully!"
+            # Perform actions for successful compilation here
           else
             echo "npm start failed!"
-            exit 1
+            # Perform actions for failed compilation here
           fi
